defaults:
 - default
 - _self_

callbacks:
  - _target_: callbacks.TerminateOnNaN
  
  - _target_: pytorch_lightning.callbacks.EarlyStopping
    monitor: "val/clf_auprc"
    patience: 30
    mode: "max"
    verbose: True

  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    dirpath: ${hydra:run.dir}/.checkpoints/max_auprc
    monitor: "val/clf_auprc"
    save_top_k: 3
    mode: "max"
    filename: "{epoch}-{val/clf_auprc:.2f}"